source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BigRest_Example', :exclusive => true do
  pod 'BigRest', :path => '../'
end

target 'BigRest_Tests', :exclusive => true do
  pod 'BigRest', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
