source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target :BigRest_Example do
  pod 'BigRest', :path => '../'
end

def testing_pods
    pod 'Specta'
    pod 'Expecta'
end

target :BigRest_Tests do
  
  testing_pods

end
